name: GitHub Actions Hello World
run-name: ${{ github.actor }} esta fazendo um hello word
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Isso foi automaticamente disparado pelo GitHub Actions. ${{ github.event_name }}."
      - run: echo "Estamos rodando em um servidor hospedado pelo GitHub. ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v4 # essa parada parece que da tipo um git clone pra maquina 'ubuntu-latest' criada
      - name: Dar ls
        run: ls # isso aqui da um ls no diretorio raiz do repo
      - name: Rodar make
        run: make
      - name: Rodar binário # aqui mais alguns comandos possiveis do yml
        run: |
          if [ -x ./hellomake ]; then
            ./hellomake
          else
            echo "O binário 'hellomake' não foi encontrado ou não é executável!" && exit 1
          fi
